Fix TypeError when initializing AsyncioThriftClient when calling get_fcr_client in service.py
Summary:
Currently the get_fcr_client would raise a TypeError since the "__init__" method in AsyncioThriftClient does not have a loop argument

Sample error message:
```
> ERROR
>
> ======================================================================
> ERROR: test_get_fcr_client_timeout (nettools.fb_command_runner.oss.tests.test_command_session.CommandSessionTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/data/users/mzheng/fbsource/fbcode/buck-out/dev/gen/nettools/fb_command_runner/oss/tests/fcr_tests#binary,link-tree/nettools/fb_command_runner/oss/tests/testutil.py", line 30, in _wrapper
>     self._loop.run_until_complete(func(self, *args, **kwargs))
>   File "/usr/local/fbcode/platform007/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
>     return future.result()
>   File "/data/users/mzheng/fbsource/fbcode/buck-out/dev/gen/nettools/fb_command_runner/oss/tests/fcr_tests#binary,link-tree/nettools/fb_command_runner/oss/tests/test_command_session.py", line 218, in test_get_fcr_client_timeout
>     self.mocks.get_fcr_client(timeout=0)
>   File "/data/users/mzheng/fbsource/fbcode/buck-out/dev/gen/nettools/fb_command_runner/oss/tests/fcr_tests#binary,link-tree/fbnet/command_runner/service.py", line 186, in get_fcr_client
>     loop=self.loop,
> TypeError: __init__() got an unexpected keyword argument 'loop'
```

Reviewed By: starskywongfb

Differential Revision: D17914816

fbshipit-source-id: 3c08f94816cf64145e8a0a8a7f7f061c2a9af232